// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login').default>>>>
    }
    '/api/auth/magic/verify': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/magic/verify').default>>>>
    }
    '/api/inventory/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/[id].put').default>>>>
    }
    '/api/inventory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/index.post').default>>>>
    }
    '/api/requests/:email': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/requests/[email].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/requests/[email].get').default>>>>
    }
    '/api/requests': {../../server/api/requests/[email].delete
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/requests/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.1_d_8c1b0685153e24bfe3e7340badec148c/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}